
services:
  satisfaction-service:
    container_name: satisfaction-service
    build: .
    ports:
      - "3008:3008"
    env_file:
      - ./.env
    networks:
      - support-network

networks:
  support-network:
    external: true
