services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - support-network
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_MS: 604800000
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_CLEANUP_POLICY: delete
      
    networks:
      - support-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1
      interval: 10s
      retries: 20
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - support-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "3001:3001"
    env_file:
      - ./api-gateway/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  auth-microservice:
    build:
      context: ./auth-microservice
    container_name: auth-services
    ports:
      - "3002:3002"
    env_file:
      - ./auth-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  ticket-microservice:
    build:
      context: ./ticket-microservice
    container_name: ticket-services
    ports:
      - "3003:3003"
    env_file:
      - ./ticket-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  notification-microservice:
    build:
      context: ./notification-microservice
    container_name: notification-services
    ports:
      - "3004:3004"
    env_file:
      - ./notification-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  user-microservice:
    build:
      context: ./user-microservice
    container_name: user-services
    ports:
      - "3005:3005"
    env_file:
      - ./user-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  customer-microservice:
    build:
      context: ./customer-microservice
    container_name: customer-services
    ports:
      - "3006:3006"
    env_file:
      - ./customer-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  project-microservice:
    build:
      context: ./project-microservice
    container_name: project-services
    ports:
      - "3007:3007"
    env_file: 
      - ./project-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  satisfaction-microservice:
    build:
      context: ./satisfaction-microservice
    container_name: satisfaction-services
    ports:
      - "3008:3008"
    env_file:
      - ./satisfaction-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  status-microservice:
    build:
      context: ./status-microservice
    container_name: status-services
    ports: 
      - "3009:3009"
    env_file:
      - ./status-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

  categories-microservice:
    build:
      context: ./categories-microservice
    container_name: categories-services
    ports:
      - "3010:3010"
    env_file:
      - ./categories-microservice/.env
    environment:
    - DEBUG=kafkajs*
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - support-network

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:

networks:
  support-network:
    driver: bridge
