
services:
  ticket-service:
    container_name: ticket-service
    build: .
    ports:
      - "3003:3003"
    env_file:
      - ./.env
    networks:
      - support-network

networks:
  support-network:
    external: true
