
services:
  auth-service:
    container_name: auth-service
    build: .
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    networks:
      - support-network

networks:
  support-network:
    external: true
