
services:
  customer-service:
    container_name: cuatomer-service
    build: .
    ports:
      - "3006:3006"
    env_file:
      - ./.env
    networks:
      - support-network

networks:
  support-network:
    external: true
