
services:
  status-service:
    container_name: status-service
    build: .
    ports:
      - "3009:3009"
    env_file:
      - ./.env
    networks:
      - support-network

networks:
  support-network:
    external: true
