
services:
  project-service:
    container_name: project-service
    build: .
    ports:
      - "3007:3007"
    env_file:
      - ./.env
    networks:
      - support-network

networks:
  support-network:
    external: true
