
services:
  notification-service:
    container_name: notification-service
    build: .
    ports:
      - "3004:3004"
    env_file:
      - ./.env
    networks:
      - support-network

networks:
  support-network:
    external: true
