
services:
  user-service:
    container_name: user-service
    build: .
    ports:
      - "3005:3005"
    env_file:
      - ./.env
    networks:
      - support-network

networks:
  support-network:
    external: true
